apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  annotations:
  generation: 1
  resourceVersion: "3525051"
spec:
  desiredState:
    interfaces:
      - bridge:
          options:
            stp: false
          port:
            - name: enp3s0
        description: An OVS with enp3s0 uplink
        name: ovs-br
        state: up
        type: ovs-bridge
    ovn:
      bridge-mappings:
        - bridge: ovs-br
          localnet: vm-network
          state: present
  nodeSelector:
    node-role.kubernetes.io/worker: ""
